spring:
  application:
    name: registry-server
# Port default EUREKA
server:
  port: 8761


eureka:
#  server:
#    eviction-interval-timer-in-ms: 1000
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds=0: